language: ruby
rvm:
  - 2.3.3

sudo: false
branches:
  only:
    - src

cache:
  cargo: false
  bundler: false

before_install:
  - # sudo apt-get -qq update
  - sudo apt-get install -y tree

install:
  - gem install jekyll
  - gem install jekyll-paginate
  - gem install jekyll-gist
  - gem install github-pages
  - gem install jekyll-sitemap
  - gem install jekyll-seo-tag
  - wget -O "$HOME/bin/mdbook" https://donaldpinckney.com/public/files/build_cache/mdbook
  - chmod +x "$HOME/bin/mdbook"
  - mdbook --version
  - # To update mdbook, uncomment below!
  - rm "$HOME/bin/mdbook"
  - curl https://sh.rustup.rs > temp.sh
  - chmod +x temp.sh
  - ./temp.sh -y
  - source $HOME/.cargo/env
  - rm temp.sh
  - cargo install --git "https://github.com/donald-pinckney/mdBook" mdbook

script: ./buildToMaster
env:
  global:
    - ENCRYPTION_LABEL: "f45b69d04d69"
    - COMMIT_AUTHOR_EMAIL: "donald_pinckney@icloud.com"

