# Permalinks

# Setup
title:            Donald Pinckney
tagline:          'Explorations in math and computer science.'
description:      'Who tinkers with math, CS, and random stuff.'
url:              http://donaldpinckney.com
baseurl:          ""
timezone:         America/Los_Angeles
exclude:          [deploy]
author:
  name:           'Donald Pinckney'
  email:          djpinckney@ucdavis.edu

paginate:         5

# Custom vars
social:
  github: donald-pinckney
  twitter: donald_pinckney

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - github-pages
  - jekyll-autolink_email
  - jekyll-sitemap
  - jekyll-seo-tag

# Sitemap stuff
sitemap:
  include_posts:
    - "/index.html"

# Plugins
plugins_dir: [jekyll-autolink_email, jekyll-sitemap, jekyll-seo-tag]