include:
    - _FontAwesome
# Permalinks

# Setup
title:            Donald Pinckney
tagline:          'Explorations in math and computer science.'
description:      'Who tinkers with math, CS, and random stuff.'
url:              https://donaldpinckney.com
baseurl:          ""
timezone:         America/Los_Angeles
exclude:          [deploy]
repo:             https://github.com/donald-pinckney/donald-pinckney.github.io
author:
  name:           'Donald Pinckney'
  email:          donald_pinckney@icloud.com

paginate:         5

# Custom vars
social:
  github: donald-pinckney
  twitter: donald_pinckney

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - github-pages
  - jekyll-sitemap
  - jekyll-seo-tag

# Sitemap stuff
sitemap:
  include_posts:
    - "/index.html"

# Plugins
plugins_dir: [jekyll-sitemap, jekyll-seo-tag]
