# Permalinks

# Setup
title:            Donald Pinckney
tagline:          'Explorations in math and computer science.'
description:      '1st year programming languages PhD student at UMass Amherst.'
url:              https://donaldpinckney.com
baseurl:          ""
timezone:         America/Los_Angeles
exclude:          [deploy]
repo:             https://github.com/donald-pinckney/donald-pinckney.github.io
author:
  name:           'Donald Pinckney'
  email:          donald_pinckney@icloud.com
school_year:      '1st'

paginate:         5
paginate_path:    "/blog/page:num/"

# Custom vars
social:
  github: donald-pinckney
  twitter: donald_pinckney
  email: 'dpinckney@cs.umass.edu'

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - github-pages
  - jekyll-sitemap
  - jekyll-seo-tag

# Sitemap stuff
sitemap:
  include_posts:
    - "/index.html"

# Plugins
plugins_dir: [jekyll-sitemap, jekyll-seo-tag]

host: 0.0.0.0
