# Permalinks

# Setup
title:            Donald Pinckney
tagline:          'Explorations in math and computer science.'
description:      'Who tinkers with math, computer science, and random stuff.'
url:              http://donaldpinckney.com
baseurl:          /

author:
  name:           'Donald Pinckney'
  email:          djpinckney@ucdavis.edu

paginate:         5

# Custom vars

social:
  github: donald-pinckney
  twitter: donald_pinckney

# Gems

gems:
  - jekyll-paginate
  - jekyll-gist
