[book]
title = "Machine Learning with TensorFlow"
description = "An introductory look at implementing machine learning algorithms using TensorFlow in Python."
author = "Donald Pinckney"
multilingual = false
src = "src"

[output.html]
mathjax-support = true
theme = "src/theme"